### ISSUE TITLE
这种库有什么意义。。。。什么人会在项目里同时使用fresco和glide，简直low到家了。

### ISSUE THREAD

**Issue by bboylin** [ladingwu/ImageLoaderFramework#12]
这种库有什么意义。。。。什么人会在项目里同时使用fresco和glide，简直low到家了。

**Comment by yinhangfeng** [comment]
库的开发者 比如图片选择

**Comment by ladingwu** [comment]
这个库对fresco和gilde是分别封装的，上层使用了统一的API，屏蔽他们的差异。并不是要你同时使用两种图片加载库。

**Comment by bboylin** [comment]
第一：两个高度重合的库不会同时在项目里用，第二：你的封装没有原作者好，画蛇添足。

**Comment by bboylin** [comment]
没有使用两个库的必要谈什么屏蔽差异

**Comment by ladingwu** [comment]
看来您并没有认真看我的回复，我再强调一遍：
1，绝对不是一个项目里面使用两种加载库，绝对不是，而且我也绝对不推荐。
2，项目中使用什么加载库就用什么封装库即可（封装总是要的吧，总不可能您引用了Glide,就直接再项目里面随处使用吧，那么，ImageLoaderFramework首先帮你做到合理封装，满足日常大部分需求）
3，当您的项目迭代到一定程度，因为业务变化，有一定概率上会涉及到底层加载库的迁移（您没经历过不代表没有哦），那么这个库能再不改动任何代码的情况下，解决这个问题。
4，封装上，确实比不上原作者，这是自然，因为我不是要做一个图片加载库，而是对它们做合理的封装，保证代码的可拓展性（这是两种不同的需求）

**Comment by bboylin** [comment]
恕我直言，迁移方面你这个库也做不了啥，除非一开始就用你这个库，否则要改多少地方还是得改多少地方。谁吃饱了没事儿干glide和fresco换着用，功能上极其相似，项目初期就该想好用啥，定制化需求就自己改源码。用这个，low，小作坊气息签名由 网易邮箱大师 定制 在2019年03月02日 10:56，ladingwu 写道： 看来您并没有认真看我的回复，我再强调一遍： 1，绝对不是一个项目里面使用两种加载库，绝对不是，而且我也绝对不推荐。 2，项目中使用什么加载库就用什么封装库即可（封装总是要的吧，总不可能您引用了Glide,就直接再项目里面随处使用吧，那么，ImageLoaderFramework首先帮你做到合理封装，满足日常大部分需求） 3，当您的项目迭代到一定程度，因为业务变化，有一定概率上会涉及到底层加载库的迁移（您没经历过不代表没有哦），那么这个库能再不改动任何代码的情况下，解决这个问题。 4，封装上，确实比不上原作者，这是自然，因为我不是要做一个图片加载库，而是对它们做合理的封装，保证代码的可拓展性（这是两种不同的需求） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
