### ISSUE TITLE
cleanMemory 的一些疑问

### ISSUE THREAD

**Issue by zhaogaofeng** [ladingwu/ImageLoaderFramework#4]
您好,仔细阅读了一下您的代码,大受启发,不过有几个问题想请教一下您:在glideImageloader 中有行注释写着:存在问题 java.lang.IllegalArgumentException You cannot start a load for a destroyed activity 按照我的理解这个问题的原因是因为传入的Context是activity导致的,代码中初始化直接传入的是全局的,按说应该不会出现这种问题呀....还有cleanMemory的问题,您在实际使用中cleanMemory是写在baseActivity/baseFragment的 onstop里的么?

**Comment by ladingwu** [comment]
java.lang.IllegalArgumentException You cannot start a load for a destroyed activity,理论上应该是你说的那个原因，但是我们在实际的项目中却很难复现这个问题，所以暂时也没有解决，你可以看看怎么复现，迫不得已，最好不要传入全局的Context，因为Glide本身会根据Context的生命周期来调整图片加载策略。cleanMemory最好放在onTrimMemory(int level)，onLowMemory() 中。
