### ISSUE TITLE
如果引入新的图片库，还是适配ImageLoaderOptions

### ISSUE THREAD

**Issue by LQG24** [ladingwu/ImageLoaderFramework#5]
如果增加Picasso 还是得在对应的Loader中把ImageLoaderOptions转成RequestCreator，然后再调用picasso接口。  Picasso.with(MainActivity.this)
                .load(IME_URL)
                .placeholder(R.mipmap.ic_launcher) //设置占位图
                .error(R.mipmap.ic_launcher_round) //加载错误图
                .into(mPicassoIV);

建议在初始化的时候传IImageLoaderstrategy。不然转化图库得这样写
 ImageLoaderManager.getInstance().setImageLoaderStrategy(new GlideImageLoader());
  ImageLoaderManager.getInstance().showImage(ImageLoaderManager.getDefaultOptions(img2,url));

**Comment by ladingwu** [comment]
你的意思是我不是很懂。。。
