### ISSUE TITLE
最新版本崩溃了

### ISSUE THREAD

**Issue by CJEEP** [ladingwu/ImageLoaderFramework#9]
FrescoImageLoader 类的105行options.getResource()==null了

**Comment by ladingwu** [comment]
收到

**Comment by ladingwu** [comment]
有没有详细的堆栈报错信息？

**Comment by ladingwu** [comment]
我大概知道是什么问题了

**Comment by WPCWEG** [comment]
这个问题，在你最新的提交里面没有得到妥善的解决，你添加了一个 “/”, 但是getResource()还是为空

**Comment by WPCWEG** [comment]
没注意看版本，我用的还是老的，你今日早上更新到0.0.8问题解决了
